// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:am_tech/config/app_config.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    final isProd = AppConfig.isProd;

    if (kIsWeb) {
      return isProd ? webProd : webDev;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isProd ? androidProd : androidDev;

      case TargetPlatform.iOS:
        return isProd ? iosProd : iosDev;

      case TargetPlatform.macOS:
        return isProd ? macosProd : macosDev;

      case TargetPlatform.windows:
        return isProd ? windowsProd : windowsDev;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase não configurado para linux.',
        );

      default:
        throw UnsupportedError(
          'Plataforma não suportada.',
        );
    }
  }

  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: 'AIzaSyDFuWS31ju4TlRhF3n30VPz6mAkx36gMIc',
    appId: '1:455823305375:web:ce42108c4e356abb1c10aa',
    messagingSenderId: '455823305375',
    projectId: 'am-tech-a633a',
    authDomain: 'am-tech-a633a.firebaseapp.com',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
    measurementId: 'G-YNET9Y6N54',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyDfqTUBt1vf3pv6mT80I5zZv3eay_LFEW0',
    appId: '1:455823305375:android:d259231d575448e91c10aa',
    messagingSenderId: '455823305375',
    projectId: 'am-tech-a633a',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyDUfbPu5FmbFcuHOjlBgZiMtkBV90bcKgM',
    appId: '1:455823305375:ios:2411e02507ea622c1c10aa',
    messagingSenderId: '455823305375',
    projectId: 'am-tech-a633a',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
    iosBundleId: 'com.example.amTech',
  );

  static const FirebaseOptions macosProd = FirebaseOptions(
    apiKey: 'AIzaSyDUfbPu5FmbFcuHOjlBgZiMtkBV90bcKgM',
    appId: '1:455823305375:ios:2411e02507ea622c1c10aa',
    messagingSenderId: '455823305375',
    projectId: 'am-tech-a633a',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
    iosBundleId: 'com.example.amTech',
  );

  static const FirebaseOptions windowsProd = FirebaseOptions(
    apiKey: 'AIzaSyDFuWS31ju4TlRhF3n30VPz6mAkx36gMIc',
    appId: '1:455823305375:web:b57308753e79893d1c10aa',
    messagingSenderId: '455823305375',
    projectId: 'am-tech-a633a',
    authDomain: 'am-tech-a633a.firebaseapp.com',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
    measurementId: 'G-DNJX03M2WN',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyC4LxvMab8el0WS7ST1NFRB3SLMFv9pr7s',
    appId: '1:925184200738:android:6dadc5c77695eb3552ba7b',
    messagingSenderId: '925184200738',
    projectId: 'am-tech---teste',
    authDomain: 'am-tech---teste.firebaseapp.com',
    storageBucket: 'am-tech---teste.firebasestorage.app',
    measurementId: 'G-YNET9Y6N54',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyBTzLQiRuOEhLqM-2UKzcbed9_ftnTwPKg',
    appId: '1:925184200738:android:3cecb66121af735252ba7',
    messagingSenderId: '925184200738',
    projectId: 'am-tech---teste',
    storageBucket: 'am-tech---teste.firebasestorage.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyDUfbPu5FmbFcuHOjlBgZiMtkBV90bcKgM',
    appId: '1:925184200738:android:6dadc5c77695eb3552ba7b',
    messagingSenderId: '925184200738',
    projectId: 'am-tech---teste',
    storageBucket: 'am-tech---teste.firebasestorage.app',
    iosBundleId: 'com.example.amTech',
  );

  static const FirebaseOptions macosDev = FirebaseOptions(
    apiKey: 'AIzaSyDUfbPu5FmbFcuHOjlBgZiMtkBV90bcKgM',
    appId: '1:925184200738:android:6dadc5c77695eb3552ba7b',
    messagingSenderId: '925184200738',
    projectId: 'am-tech---teste',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
    iosBundleId: 'com.example.amTech',
  );

  static const FirebaseOptions windowsDev = FirebaseOptions(
    apiKey: 'AIzaSyDFuWS31ju4TlRhF3n30VPz6mAkx36gMIc',
    appId: '1:925184200738:android:6dadc5c77695eb3552ba7b',
    messagingSenderId: '925184200738',
    projectId: 'am-tech---teste',
    authDomain: 'am-tech---teste.firebaseapp.com',
    storageBucket: 'am-tech-a633a.firebasestorage.app',
    measurementId: 'G-DNJX03M2WN',
  );
}
